### ISSUE TITLE
How does the webpack integration work once deployed?

### ISSUE THREAD

**Issue by thatandyrose** [chrisvfritz/rails-javascript-integrations#2]
Hi @chrisvfritz, thanks for this repo, really useful!

I was looking at the vue-webpack solution and see it works by simply having webpack run alongside `rails s` and you've just put the directory "IN" the rails directory.

however... once you run `npm run build` where do the files go? And my real question is... once it's built and deployed to say Heroku, how does going to say "http://myvueapp.herokuapp.com" redirect to the built frontend files....?

thanks!

**Comment by chrisvfritz** [comment]
The files go into the `public` directory. This is configured [here](https://github.com/chrisvfritz/rails-javascript-integrations/compare/master...vue-webpack#diff-f576cf165b9df501fd5cb5400c3f1761R5).

**Comment by chrisvfritz** [comment]
I haven't heard anything, so I'll assume this resolves the issue. 😃
